language: r
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - VAULTR_TEST_SERVER_BIN_PATH=$PWD/.vault
    - VAULTR_TEST_SERVER_INSTALL=true
    - VAULTR_TEST_SERVER_PORT=18200
