language: r
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

before_script:
  - inst/server/install-server.R $HOME/bin

env:
  - VAULTR_TEST_SERVER_PORT=18200
  - secure: "S7z8TRduPlMfQK5wJOSgdmm1Z/nAI2Vl5iT4/SHkoLJgNmXXpLx+lzcpAQT286QBR/BngU+1OvzhcbXGNstEIklgEvi9CUJ6u4tmVXlNFd2bqXixMB0hTJvVuovpMCCIjUJXMH4wPbsHCsMyNX7TkR/GaKebEEDl5pvnQotbyVUcZ3mtfEBtNQB2/pihFARBTtaOZAIJEG02lRW5/aFin7B5Q2VVQhDSds0P4vbZ/N1v+pymM+jnHJBsUkrdfktg6/lONZmDydTF2F0fg8feyYzM6WW5APW017HUW9fjPZtBUsFQ/1s92Djjt4LTkADHUPYGNfwjE+1Lq7l4eTSONGrJCFQG7LH38vPli7khQ3hva6axhCQLbWAWmNqbkcSUALOJZPUjwjQdrWN1y+7Vj/gmvczz8Ic4aDFRBIAo/N/IaOsfaEgkmIDkFkzMNpjBST7FX570loeCfbeVP3eEiT+iOyW1LhKss9ffmnJSMW9k6xbcEt2uRHvJMtC+9mEMzCcLzKNTX1kHQDQVG/sebZQx/QXyfWIT5zthBz4FZTNGe41pbjhLrXp7EA7zT2MfzI3zAONyWvh127wIsZUK4olRDY90rcEWoqybiv9KClofPb66RpRqOrMrbuL9ERCFA2pAqnyYlf64AdfKOeGnFtAkLCp30fSb69czWvd7P20="
